/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function computeDiff(original: string, modified: string): DiffResult

export interface DiffResult {
  diff: string
  hasChanges: boolean
}

export declare function generateDiff(filePath: string, original: string, modified: string, config?: NapiDiffConfig | undefined | null): Promise<NapiFileDiff>

export interface NapiDiffConfig {
  contextLines?: number
  color?: boolean
  maxLinesPerFile?: number
}

export interface NapiFileDiff {
  path: string
  diffText: string
  additions: number
  deletions: number
}
