/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DiffConfig {
  contextLines?: number
  maxLinesPerFile?: number
}

export interface FileDiff {
  path: string
  diffText: string
  additions: number
  deletions: number
}

export function generateDiff(
  filePath: string,
  original: string,
  modified: string,
  config?: DiffConfig | undefined | null
): Promise<FileDiff>
